#+title: Помогает ли Zettelkasten писать статьи?
#+SETUPFILE: ../../setup.org
#+HTML_HEAD: <script src="https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.32.2/tocbot.min.js"></script>

#+STARTUP: inlineimages
#+HTML_HEAD: <meta name="description" content="Разбираемся, как на самом деле работает метод Zettelkasten: помогает ли система заметок Лумана писать статьи и книги, почему не стоит ждать автоматического результата, и как избежать прокрастинации при работе с заметками." />


#+BEGIN_EXPORT html
<div class="meta-info">
  <span>Сидоров Ф., опубликовано: 2025-05-05, обновлено: 2025-09-05</span>
</div>
<nav class="js-toc toc-right"></nav>
#+END_EXPORT
Метод Цеттелькастен предлагает построить «второй мозг» из заметок, стать нашим собеседником и даже машиной для публикаций. Я изучал систему, читал статьи, менял приложения для заметок. Но за это время не написал ни одной статьи. И вот решил отложить всё в сторону и понять, почему так происходит. Помогает ли Zettelkasten писать статьи?

Цеттелькастен разработан немецким социологом Никласом Луманом для работы над общей социологической теорией. Он создал систему заметок с уникальным номером для работы с научными источниками и складывал их в каталожный ящик. Отсюда система и получила своё название: Zettelkasten дословно переводится как «ящик для заметок» или slip box.

Мы пытаемся применить этот сложный и медленный академический подход к управлению знаниями в наше быстрое цифровое время. И во всём этом мы упускаем главное, для чего он создал картотеку, — для того, чтобы писать. И, как ни странно, писательская деятельность Лумана уходит на второй план. Кажется, что Луман только и занимался картотекой, а статьи и книги появлялись сами собой. Но Цеттелькастен сам за вас статьи не напишет. Более того он может отвлекать от  создания своего контента.


* Zettelkasten не генерирует статьи автоматически
Есть миф, который пришёл из книги «How to Take Smart Notes» Зонке Аренса. Книга с самого начала обещает:

#+BEGIN_QUOTE
«Представьте, что не надо начинать с чистого листа. Вместо этого некий дружелюбный джинн… подготовил для вас черновик вашей письменной работы. Это уже полностью разработанный текст… Осталось только отредактировать готовый вариант и отправить его».
#+END_QUOTE

Автор намекает, что можно просто собирать заметки, и без всякого труда из этого что-то получается. Для этого он приводит цитату Лумана:

#+BEGIN_QUOTE
«Я никогда не заставлял себя делать то, чего мне не хочется. Всякий раз, когда я застреваю, я переключаюсь на что-то другое».
#+END_QUOTE

Когда я начал читать про картотеку Лумана, мне показалось, что цеттелькастен — это инкубатор статей, аналоговая нейросеть, в которую скармливаются заметки и которая сама выстраивает их в почти готовые черновики. Я делал заметки, переносил их из одного приложения в другое, но черновиков так и не появлялось.

Почему так происходит? Потому что никто не снимет ответственности за написание статьи. Чтобы написать статью, нужно её задумать и начать, решить, о чём писать. До этого момента заметки остаются просто разрозненными идеями.

Луман также не писал статьи в Zettelkasten, как в приложении для заметок. Он работал над текстами отдельно — в черновиках и рукописях. Картотека не была средой для работы над писательскими проектами или местом для планирования. Хотя сейчас многие советуют использовать заметки-хабы[fn:1] для создания плана текста, это — отступление от изначального подхода. Луман скорее использовал сами карточки как каркас и план статьи.

Но миф о готовых черновиках родился не на пустом месте. Особенность метода цеттелькастен состоит в том, что за счёт внутреннего ветвления заметок (что лучше всего работает при использовании иерархической нумерации) по некоторым темам могут складываться длинные мыслительные цепочки и кластеры идей, которые похожи на статьи. Но это не статьи. Даже «вечнозелёные»[fn:2] заметки, которые предлагает Энди Матушак, не являются статьями.

Работа с картотекой всегда была тесно связана с писательским проектом, а такой проект у Лумана был всегда. Картотека не была просто архивом для
коллекционирования карточек, и картотека не делала писательство автоматическим. На первом месте стояла работа с текстом. Именно ей подчинялась работа с цеттелькастен, а не наоборот. Цеттелькастен сам по себе не производил статьи.

При всём том, что цеттелькастен имел сложную структуру и систему ссылок, его ценность заключалась в том, что у Лумана всегда был конкретный писательский проект — исследовательский вопрос, который он задавал своей картотеке. Не картотека создавала для него черновики или статьи, как хочется думать, а он сам работал с ней, имея чёткую цель.


* Нужно писать черновики 
Нашел видео[fn:3] на канале Скотта Шепера[fn:4] с гостевым постом одного из авторов, которого он обучает. В нём автор делится опытом как он писал книгу с помощью цеттелькастен.

На видео стол завален карточками. Некоторые исписаны текстом и идеями, другие содержат скетчи, третьи заполнены диаграммами. При этом автор отмечает, что большинство этих карточек не были использованы при написании книги.

Затем он показывает блокнот с рукописным текстом, подчёркивает что важно писать черновики. Он объясняет, что недостаточно просто собирать заметки — необходимо иметь конкретный писательский проект, потому что процесс создания заметок и написания черновиков принципиально различается. При работе над черновиком идеи начинают соединяться по-новому, рождаются новые мысли, происходит осмысление накопленного материала.

Далее автор показывает листы с рукописью, которую перевел в печатный формат, отмечая, что даже на этом этапе он многократно вносил правки — вычеркивал целые страницы и перепечатывал их заново.

В заключение он демонстрирует готовую книгу, рассказывая о том, как лично занимался дизайном каждой страницы.

Автор выделяет *три этапа работы*:

1. *Генерация и сбор идей:* работа с цеттелькастен: чтение источников, упорядочивание карточек.
2. *Написание первого черновика:* "выплескивание" слов на бумагу.
3. *Редактирование и дизайн:* доведение текста до формата, интересного читателю.

Вывод: накопление заметок само по себе не приводит к созданию текста. Наличие конкретного писательского проекта делает работу с картотекой целенаправленной и осмысленной. Ведение заметок — вспомогательный исследовательский этап, который не обязательно должен быть организован по принципу цеттелькастен.


* Zettelkasten может стать прокрастинацией
Почему работа с цеттелькастен не приводит к результату? Пототому что требует больших вложений в организацию карточек, настройку приложений, особенно если это бумажный вариант.

Луман говорил, что работа с картотекой занимала значительное время. И на этом этапе можно начать прокрастинровать, избегая главного - написания статьи. Тут не хватает здоровой глупости - способности просто взять и сделать. В нашем случае - начать писать. 

Как работает этот механизм прокрастинации? Сначала мы увлекаемся созданием идеальной системы ссылок, подбираем "правильный" инструмент, копим заметки... Потом оказываемся в тупике: картотека превращается в свалку, в голове хаос. Мы читаем ещё больше "продвинутых" статей, меняем софт, наивно надеясь, что в какой-то момент произойдёт чудо.

Но чуда не случится. Картотека будет бесконечно разрастаться - вот и весь "результат". Если цель - обучатья и накапливать знания, тогда всё в порядке. Но если хочется создавать что-то своё и делиться знаниями, то цеттелькастен скорее мешает, чем помогает. А карточки - всего лишь вспомогательный инструмент, который легко превращается в самоцель.


* Для написания статьи нужно 2-3 карточки
Выходит, что карточки как будто и не нужны, когда пишешь статью. Статью можно написать и без них. Если же вы провели исследование, то благодаря написанию карточек и переформулированию мыслей основные идеи уже должны уложиться у вас в голове. Теперь нужно просто начать писать.

Но всё же как использовать цеттелькастен при написании статьи? Тут есть несколько возможных подходов:

1. *Написать структурный план и подставить в него карточки*. Сюда относится любой вариант, когда вы составляете скелет или тезисный план статьи, а потом «навешиваете» на него ссылки или ID карточек. Есть также интересный способ Кэла Ньюпорта: вы прямо копируете текст цитат или заметок в тезисный план и затем разом пишете текст.

2. *Разложить бумажные карточки на столе наподобие коллажа*. Таким образом можно визуализировать структуру статьи. Это близко к тому, что делал сам Луман.

3. *Создавать структурные заметки, в которых можно планировать статьи*. Но это уже не оригинальный метод, а скорее доработка подхода.

Мне подошёл такой способ — взять заголовок статьи и подобрать 3–4 карточки с основными тезисами, которые будут раскрываться в тексте. Для примера это выглядело так:

#+BEGIN_SRC
Как писать статьи с Zettelkasten?
- цеттелькастен — не генератор статей
- нужно писать черновики
- цеттелькастен = прокрастинация
#+END_SRC
 
Я не конструировал статью полностью из карточек, а использовал карточки как идеи для модулей текста. Иногда в процессе я обнаруживал пробел в понимании и возвращался на новый виток исследования, чтобы усилить аргументы. Тогда в ходе чтения создавал ещё заметки и «пришивал» их к тематическому кластеру, чтобы не потерять.

Ещё вот когда действительно полезны карточки. Когда написал абзац ссылаясь на удачную мыль из книги и кажеться, что помнишь откуда она. Но в процессе многокрастного редактирования, это забывается и когда нужно расставлять ссылки на источник, ты начинаешь искать где это было. По идее на этот случай должна быть карточка в Zettelkasten с точной ссылкой на первоисточник.

Получается, что степень использования карточек зависит от типа работы. Для научных статей важна насыщенность ссылками и источниками, тогда как для блогов требования к цитированию значительно ниже. Если вы не работаете в академической среде, строгое соблюдение всех канонов системы Лумана может быть избыточным. Не стоит переживать, если вы не собираете статью из карточек как конструктор — это совершенно не обязательно. Более того, тексты карточек не должны механически переноситься в готовую статью.

Сколько бы я ни пытался конструировать или писать текст с помощью карточек, в процессе написания и редактирования тезисы меняются до неузнаваемости, появляются новые, и от исходного плана почти ничего не остаётся. Сам Луман не копировал содержание заметок в статьи, а использовал их для синтезирования лучших аргументов за счёт неожиданных пересечений в картотеке.

Для меня картотека скорее больше ценна тем, что помогает структурировать мысли перед написанием. Но писать я уже начинаю из головы.

* Выводы

1. Работа с цеттелькастен и написание текстов — это параллельные процессы. Цеттелькастен не является инструментом, через который напрямую пишутся статьи. Это миф, что из карточек можно собрать почти готовые черновики.

2. Высок шанс, что цеттелькастен просто не нужен для написания статьи, особенно если речь не об академических дисциплинах. Более того, он может даже стать формой прокрастинации.

3. Цеттелькастен — отличный инструмент для предварительного ресёрча, организации идей и знаний, но на этапе написания он помогает не так сильно и иногда даже мешает. «Zettelkasten как машина для публикации» — скорее маркетинговый миф.



[fn:1] Некоторые сторонники метода Zettelkasten предлагают делать [[https://zettelkasten.de/posts/three-layers-structure-zettelkasten/][структурные заметки]] или заметки-хабы, например для планирования структуры статьи или создания иерархии заметок на подобие раздела. [[https://zettelkasten.de/posts/zettelkasten-hubs/][Заметки-хабы]] использовал сам Луман, но не для планирование текстов.

[fn:2] Энди Матушак - известный в PKM сообществе программист, дизайнер, исследователь. Он автор [[http://notes.andymatuschak.org/Evergreen_notes][идеи вечнозелёных заметок]]. Это своего рода заметки-концепты, которые развиваются со временем.

[fn:3] [[https://www.youtube.com/watch?v=cvs5Hu1zzzk][How to Write a Book Using a Zettelksten]]

[fn:4] [[https://www.youtube.com/@scottscheper][Скотт Шеппер]] американский автор, который активно продвигает полностью аналоговый-бумажный подход к ведению заметок. Обучает авторов писать и зарабатывать на писательстве с Zettelkasten.

#+BEGIN_EXPORT html
<script>
tocbot.init({
  // Where to render the table of contents.
  tocSelector: '.js-toc',
  // Where to grab the headings to build the table of contents.
  contentSelector: '.content',
  // Which headings to grab inside of the contentSelector element.
  headingSelector: 'h1, h2, h3',
  // For headings inside relative or absolute positioned containers within content.
  hasInnerContainers: true,
  orderedList: false,
  ignoreSelector: '.footnotes'
});
</script>
#+END_EXPORT
