name: Deploy to External Server

on:
  push:
    branches:
      - main  # Adjust to your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EXTERNAL_HOST }}
          username: ${{ secrets.EXTERNAL_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # Change if needed
          source: "./"  # Files to upload
          target: "/home/c/cw28483/filippsidorov.ru/public_html"  # Your external host web root

